language: python
python:
  - "2.7"

install:
    - travis_retry pip install tox==1.8
script:
    - tox -e py27
after_success:
    - tox -e py27-coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

deploy:
  provider: heroku
  app: funsize-dev
  api_key:
    secure: hnbpyFSwGNNSulYsfMJLp0g/pB7xDGtWw3X2OLw5tYd1ha44JSP61qOzZO1SceI4s6p3lej9Vn6hFwASzU/v8rGtyP/o3UkUwK/+Pg4+TnJgrvbg+dtmfuQXcKJVVFvI9dk6T/VVMkl26Rs5/dMlmjHg25WrTEX49RlAYhgQYjw=
