---
balrog:
    username: null
    password: null
    api_root: https://aus4-admin-dev.allizom.org/api
    # usually needed if using https://aus4-admin.mozilla.org/api as the api_root
    # cert: funsize/data/mozilla-root.crt
    # linked worker:1
    worker_api_root: http://balrog/api

pulse:
    user: null
    password: null
    queue: funsize
    exchange: "exchange/build/"

taskcluster:
    credentials:
      clientId: null
      accessToken: null
s3:
    bucket: null
    aws_access_key_id: null
    aws_secret_access_key: null
